export const SET_CURRENT_IMAGE_REGISTRATION = 'SET_CURRENT_IMAGE_REGISTRATION';
export const DELETE_CURRENT_IMAGE_REGISTRATION =
  'DELETE_CURRENT_IMAGE_REGISTRATION';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_CURRENT_USER_IMAGE = 'ADD_CURRENT_USER_IMAGE';
export const CLEAR_CURRENT_USER_IMAGES = 'CLEAR_CURRENT_USER_IMAGES';
